### ISSUE TITLE
Does it really use the SSH-Keys from the Bamboo-Stash integration

### ISSUE THREAD

**Issue by heebj** [dewet22/bamboo-lfs#1]
> No passwords or ssh keys needed, it reuses the existing Bamboo-Stash integration

Does this mean that when I configure a Bitbucket plan repository in Bamboo, the script uses the SSH key generated by bamboo to clone repository? How is this working, the script does not do anything with a key...

I have to rewrite the script for Windows but if everything works as expected it would be fantastic and is exactly what I was looking for! Thanks for sharing your work!

**Comment by dewet22** [comment]
Yup, I just tested it in Bamboo by setting up a new "linked repository" to a clean Stash repo. It automatically installs its own SSH key in the stash repo, so it works pretty seamlessly. You can verify this on the stash side by going to the repo settings and looking under "access keys" -- there should be one named https://bamboo.yourdomain.com (or similar).

This script just uses normal `git clone` using the "real" stash repo as origin -- see line 5 -- but essentially Bamboo supplies this as the `$bamboo_planRepository_repositoryUrl` environment variable. git just reuses the ssh keys of the user bamboo is running as, which should match the one automatically installed above.
